MERGE INTO VIDEO_SEARCH_QUERY AS T
USING (
    VALUES {{ ti.xcom_pull(task_ids="prepare_video_query_data_task") }}
) AS S(YOUTUBE_VIDEO_ID, QUERY)
ON T.YOUTUBE_VIDEO_ID = S.YOUTUBE_VIDEO_ID AND T.QUERY = S.QUERY
WHEN NOT MATCHED THEN
    INSERT (YOUTUBE_VIDEO_ID, QUERY) VALUES (S.YOUTUBE_VIDEO_ID, S.QUERY)