MERGE INTO YOUTUBE_VIDEO T
USING (
    VALUES {{ ti.xcom_pull(task_ids="extract_videos_full_info_task") }}
) S(ID, ETAG, TITLE, DESCRIPTION, CHANNEL_ID, PUBLISHED_AT, DURATION)
ON T.ID = S.ID
WHEN MATCHED THEN
    UPDATE SET ETAG = S.ETAG, TITLE = S.TITLE, DESCRIPTION = S.DESCRIPTION, CHANNEL_ID = S.CHANNEL_ID, PUBLISHED_AT = S.PUBLISHED_AT::timestamp, DURATION = S.DURATION
WHEN NOT MATCHED THEN
    INSERT (ID, ETAG, TITLE, DESCRIPTION, CHANNEL_ID, PUBLISHED_AT, DURATION) VALUES (S.ID, S.ETAG, S.TITLE, S.DESCRIPTION, S.CHANNEL_ID, S.PUBLISHED_AT::timestamp, S.DURATION)